blank_issues_enabled: false
contact_links:
  - name: ğŸ“œ Uygunsuz Ä°Ã§eriÄŸi Bildir
    url: https://github.com/BKT-DevOps/project-terraform-github/issues/new?template=report-abuse.yml
    about: Taciz, nefret sÃ¶ylemi veya davranÄ±ÅŸ kurallarÄ±na aykÄ±rÄ± iÃ§erikleri bildirmek iÃ§in kullanÄ±n.

  - name: âœ… Yeni GÃ¶rev OluÅŸtur
    url: https://github.com/BKT-DevOps/project-terraform-github/issues/new?template=task.yml
    about: Proje yÃ¶netimi ve geliÅŸtirme gÃ¶revleri iÃ§in kullanÄ±n.

  - name: ğŸ› Hata Bildir
    url: https://github.com/BKT-DevOps/project-terraform-github/issues/new?template=bug-report.yml
    about: YazÄ±lÄ±m hatalarÄ±nÄ± ve beklenmeyen davranÄ±ÅŸlarÄ± bildirin.

  - name: ğŸ’¡ Ã–zellik Ä°steÄŸi
    url: https://github.com/BKT-DevOps/project-terraform-github/issues/new?template=feature-request.yml
    about: Yeni Ã¶zellik Ã¶nerinizi veya geliÅŸtirme fikirlerinizi paylaÅŸÄ±n.

  - name: ğŸ’¬ Topluluk TartÄ±ÅŸmalarÄ±
    url: https://github.com/BKT-DevOps/project-terraform-github/discussions
    about: Sorular ve fikirler iÃ§in topluluk tartÄ±ÅŸmalarÄ±na katÄ±lÄ±n.

  - name: ğŸ“– DokÃ¼mantasyon
    url: https://github.com/BKT-DevOps/project-terraform-github/wiki
    about: Proje dokÃ¼mantasyonunu ve kÄ±lavuzlarÄ± inceleyin.